### ISSUE TITLE
Write docker scripts for deploying and running dist extraction framework.

### ISSUE THREAD

**Issue by nilesh-c** [gone-phishing/docker-distributed-extraction#2]
Make extraction config.properties and dist-config.properties configurable. User should supply the script. One shouldn't need to modify the git repository to make such changes.

Take the help of the the existing GCE script to learn what stuff to setup (eg. build spark with scala 2.11 and hadoop, setup HDFS, etc.).

Aim for single-node setup first.

**Comment by gone-phishing** [comment]
Cool, I'll look into this

**Comment by gone-phishing** [comment]
Added the functionality to use user defined config files

**Comment by gone-phishing** [comment]
Updated gce script to install spark_1.3.0 with scala_2.11.4
